security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Newscoop\Entity\User:
            id: newscoop_newscoop.password_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [backend_db, simple]
        simple:
            id: newscoop_newscoop.simple_user_provider
        backend_db:
            entity: { class: Newscoop\Entity\User, property: username }
        frontend_db:
            entity: { class: Newscoop\Entity\User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        password_recovery:
            pattern: ^/admin/password-recovery
            security: false

        password_check_token:
            pattern: ^/admin/password-check-token
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            provider: backend_db
            form_login:
                use_forward: true
                login_path: /oauth/v2/auth_login
                check_path: /oauth/v2/auth_login_check
                success_handler: newscoop_newscoop.security.oauth.success_handler
            logout:
                path:   /oauth/v2/auth/logout
                target: /oauth/v2/auth
                success_handler: newscoop_newscoop.security.oauth.logout.success_handler

        api:
            pattern:    ^/(api|content\-api)
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        admin_area:
            pattern:    ^/admin
            provider: chain_provider
            form_login:
                use_forward: true
                login_path:  admin_login
                check_path:  admin_login_check
                success_handler: newscoop_newscoop.security.authentication.success_handler
            remember_me:
                key: "%kernel.secret%"
                lifetime: %remember_me.lifetime%
                path: /
                domain: ~
            logout:
                path: admin_logout
                target: /admin
                invalidate_session: false
                success_handler: newscoop_newscoop.security.logout.success_handler

        frontend_area:
            pattern:    ^/
            provider: frontend_db
            form_login:
                login_path:  /auth
                check_path:  /auth
                username_parameter: email
                password_parameter: password
                success_handler: newscoop_newscoop.security.authentication.frontend.success_handler
            remember_me:
                key: "%kernel.secret%"
                lifetime: %remember_me.lifetime%
                path: /
                domain: ~
            logout:
                path: /auth/logout
                target: /
                invalidate_session: false
                success_handler: newscoop_newscoop.security.frontend.logout.success_handler
            anonymous:  true

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
